<?php

/**
 * File: people.inc
 * Author: Ryan Prather
 * Purpose: Represents a person
 * Created: Dec 8, 2014
 *
 * Portions Copyright 2016-2017: Cyber Perspectives, LLC, All rights reserved
 * Released under the Apache v2.0 License
 *
 * Portions Copyright (c) 2012-2015, Salient Federal Solutions
 * Portions Copyright (c) 2008-2011, Science Applications International Corporation (SAIC)
 * Released under Modified BSD License
 *
 * See license.txt for details
 *
 * Change Log:
 *  - Dec 8, 2014 - File created
 *  - Sep 1, 2016 - Updated Copyright and added comments
 */

/**
 * Represents the people that will be working on an assessment
 *
 * @author Ryan Prather
 */
class people {

  public $id = 0;
  public $name = '';
  public $org = '';
  public $phone = '';
  public $position = '';

}
