<?php

/**
 * File: base.inc
 * Author: Ryan Prather
 * Purpose: The purpose of this file is to hold any constants that are used throughout the program
 * Created: 6 Jan 2014
 *
 * Portions Copyright (c) 2012-2015, Salient Federal Solutions
 * Portions Copyright (c) 2008-2011, Science Applications International Corporation (SAIC)
 * Released under Modified BSD License
 *
 * See license.txt for details
 *
 * Change Log:
 *  - 6 Jan 14 - File created
 */
/**
 * Public array to store the states for drop downs, etc
 */
$STATES = array(
  ''   => ' -- Please Select An Option -- ',
  'AL' => 'Alabama',
  'AK' => 'Alaska',
  'AZ' => 'Arizona',
  'AR' => 'Arkansas',
  'CA' => 'California',
  'CO' => 'Colorado',
  'CT' => 'Connecticut',
  'DE' => 'Deleware',
  'DC' => 'District of Columbia',
  'FL' => 'Florida',
  'GA' => 'Georgia',
  'HI' => 'Hawaii',
  'ID' => 'Idaho',
  'IL' => 'Illinois',
  'IN' => 'Indiana',
  'IA' => 'Iowa',
  'KS' => 'Kansas',
  'KY' => 'Kentucky',
  'LA' => 'Lousiana',
  'ME' => 'Maine',
  'MD' => 'Maryland',
  'MA' => 'Massachusetts',
  'MI' => 'Michigan',
  'MN' => 'Minnesota',
  'MS' => 'Mississippi',
  'MO' => 'Missouri',
  'MT' => 'Montana',
  'NE' => 'Nebraska',
  'NH' => 'New Hampshire',
  'NJ' => 'New Jersey',
  'NM' => 'New Mexico',
  'NV' => 'Nevada',
  'NY' => 'New York',
  'NC' => 'North Carolina',
  'ND' => 'North Dakota',
  'OH' => 'Ohio',
  'OK' => 'Oklahoma',
  'OR' => 'Oregon',
  'PA' => 'Pennsylvania',
  'RI' => 'Rhode Island',
  'SC' => 'South Carolina',
  'SD' => 'South Dakota',
  'TN' => 'Tennessee',
  'TX' => 'Texas',
  'UT' => 'Utah',
  'VA' => 'Virgina',
  'VT' => 'Vermont',
  'WA' => 'Washington',
  'WV' => 'West Virgina',
  'WI' => 'Wisconsin',
  'WY' => 'Wyoming'
);

/**
 * Public array to store countries where we have systems
 */
$Countries = array(
  ''   => ' -- Please Select An Option -- ',
  'AI' => 'Ascension Island',
  'KI' => 'Kwajalein Island',
  'DG' => 'Diego Garcia',
  'US' => 'United States'
);
